### ISSUE TITLE
Overwritten sudoers file

### ISSUE THREAD

**Issue by drak42** [starlilyth/Linux-PoolManager#1]
Hi,

Ran your install script and I am now unable to sudo anyhting as it seems my password has been changed.

Any thoughts?

Would really like to get this tool going.

On Ubuntu Linux Server

**Comment by starlilyth** [comment]
No passwords are changed in the installation of PoolManager, but it does append lines to /etc/sudoers. Your original sudoers file was copied to sudoers.pre-ifmi before the changes took place, so you can copy/rename it back to restore your original functionality. 
I am interested to know where the install went wrong there.

**Comment by drak42** [comment]
Thanks, for getting back to me, I'll have to do this when back in front of the machine and booted from a repair disk. Don't have rights to replace it currently. Will try and let you know.

**Comment by drak42** [comment]
Hi, managed to fix it, by enabling the root account and then resetting the root password with sudo passwd.

The sudo files were identical, except for the last two lines that get added. don't think it's related to your script.

Now to get that working :)

**Comment by starlilyth** [comment]
Excellent. I will close this then.

**Comment by drak42** [comment]
Hi, tried this again on a fresh Ubuntu 12.04 LTS install and got the same result. After running the install script I cannot sudo. 

Might be something that does need further investigation.

Cheers
Chris

**Comment by starlilyth** [comment]
Are you running the install-pm.sh as root, or using sudo?

**Comment by drak42** [comment]
running as sudo

**Comment by starlilyth** [comment]
Please try as root, not sudo. Do: sudo su -
Then cd to the directory, and do: ./install-pm.sh

**Comment by drak42** [comment]
ok.. thats much better thanks!
I get the following though now, cp: cannot stat '/opt/ifmi/pmgraph.pl': No such file or directory

Also, I get 500 Internal server error when accessing the URL

**Comment by starlilyth** [comment]
I have fixed the cp error from install-pm. This was non fatal, it simply missed backing up the file on re-install.

**Comment by starlilyth** [comment]
"Also, I get 500 Internal server error when accessing the URL"
Which URL? Please try 'apachectl restart' and see if this doesnt correct the error

**Comment by drak42** [comment]
Hi,

Sorry for taking so long to get back to you. The apachectl restart made no difference.

http://192.168.1.41/cgi-bin/status.pl is the URL that is coming up when accessing the box.

Thanks
Chris
