### ISSUE TITLE
When ran on Ubuntu it changed rights on /etc/sudoers to only 440

### ISSUE THREAD

**Issue by pmalek** [starlilyth/Linux-PoolManager#21]
After running the `./install-pm.sh` it changed `/etc/sudoers` rights to `440` and I cannot edit it now unless connected to recovery console.

```
$ ll /etc/sudoers
-r--r----- 1 root root 823 mar  7 16:07 /etc/sudoers
```

on each sudo command I get : 

```
[sudo] password for root: 
```

**Comment by starlilyth** [comment]
These are the correct file permissions for /etc/sudoers. 
The installer makes a backup before modifying the file. The original is named /etc/sudoers.pre-ifmi, and can be copied back if there is a problem. 
The installer adds two lines that allow the webpage to execute commands as a given user. Please see the README for details.  

I am interested to know how this went wrong for you. Can you provide more details please? Is this BAMT or a plain Linux? Did you execute the installer as root, or did you use sudo? 

Thanks, Lily

**Comment by pmalek** [comment]
I use Ubuntu 13.10, I have ran it with `sudo ./install-pm.sh` since it gave me problems while running without it.
I have restored my `/etc/sudoers` file and now it is ok.

**Comment by starlilyth** [comment]
Please run the install script AS ROOT, not with sudo. As as user, do: sudo su -
This will make you root with the correct environment. Then you will be able to execute install-pm.sh without errors. 
If you install using these steps, and still have a problem, please open another issue and I will work with you to fix it. 

Thanks!

**Comment by pmalek** [comment]
I have just checked and the problem is with the line

```
Defaults targetpw
```

 that you are adding to the `/etc/sudoers`. Immediately after removing solely this line I get asked for password my user  (being in sudo group) instead of the password of `root` on any `sudo` command.

**Comment by starlilyth** [comment]
Correct. That line allows PoolManager to execute commands as another user with their password - e.g. stop/start the miner as root. 

Normally /etc/sudoers looks like this: 
root    ALL=(ALL) ALL
user  ALL=(ALL) ALL: ALL

Where user is a user account. This allows normal function that you expect. 
PoolManager adds these lines to the end: 
Defaults targetpw
www-data ALL=(ALL) /usr/sbin/mine,/bin/cp,/sbin/coldreboot,/opt/ifmi/mcontrol

The file is read sequentially, so only users after the Defaults line are affected by it. Be certain your user line is above the Defaults line, to prevent being affected by it.

**Comment by pmalek** [comment]
That is almost exactly how my `/etc/sudoers` file looks like : 

```
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# User privilege specification
root    ALL=(ALL:ALL) ALL
USER  ALL=(ALL:ALL) NOPASSWD:ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d
Defaults targetpw
www-data ALL=(ALL:ALL) /opt/ifmi/mcontrol,/bin/cp,/sbin/reboot
```

**Comment by starlilyth** [comment]
This appears correct, so I am uncertain why you would be affected by a directive that appears after the specification that matches your user account - only www-data should be affected by the targetpw directive. Try commenting it out and see if everything behaves as expected.

**Comment by pmalek** [comment]
Well I do not want to dispute if that is correct or not but I am certain that on my system only adding/removing the line `Defaults targetpw` changes the deal.
Now I have successfully run this tool (with apache) and I have removed the aforementioned line and it works fine so we have to somehow note that down so that other Ubuntu (and maybe some other distro) users won't break their systems just as I have done.
So far I have not noticed any malfunctions while using your software without the `Deafults targetpw` line.
