### ISSUE TITLE
Not found "The requested URL /cgi-bin/status.pl was not found on this server."

### ISSUE THREAD

**Issue by pmalek** [starlilyth/Linux-PoolManager#22]
After installing using `root` user I have the following message while accessing the server: 

```
Not Found

The requested URL /cgi-bin/status.pl was not found on this server.

Apache/2.4.6 (Ubuntu) Server at 192.168.1.166 Port 443
```

```
# ll /var/www
total 24
drwxr-xr-x  3 root root 4096 mar  7 16:07 ./
drwxr-xr-x 14 root root 4096 mar  7 16:05 ../
-rw-r--r--  1 root root  286 mar  7 16:07 favicon.ico
drwxr-xr-x  4 root root 4096 mar  7 16:07 IFMI/
-rw-r--r--  1 root root   94 mar  7 16:07 index.html
-rw-r--r--  1 root root  177 mar  7 16:07 index.html.pre-ifmi
```

Am I missing some packages ? Can you point out which ones ?

**Comment by starlilyth** [comment]
The file is in /usr/lib/cgi-bin. You will need to check your Apache configuration regarding cgi file execution.

**Comment by pmalek** [comment]
**Drunk debugging time!**

I have just tried it once again (after coming back after the party - one would not believe how creative you can be in programming when you have some alcohol in your blood :) ) and the conclusion is : 
while using Ubuntu you have to install **at least** as I have not tested if that needs anything more: 
- `libjson-perl`
- `libyaml-perl`

Please add this to the script to ensure that dependencies are installed or at least mention in the readme.

**Comment by starlilyth** [comment]
Perfect, thank you! I have added the modules to the README. I will include the dependency checks to the installer when I rewrite it in perl :)
