### ISSUE TITLE
Getting a 500 error now after I updated with a git pull and re-install

### ISSUE THREAD

**Issue by jedimstr** [starlilyth/Linux-PoolManager#23]
I had Linux-PoolManager (and BAMT PoolManager previously) installed and working.

Saw a bunch of "major" changes in the commit history, so did a git pull and re-installed, but now I'm getting a 500 error trying to access my miner.

**Comment by jedimstr** [comment]
Turns out the reinstall this time returned poolmanager.conf back to default settings.  I had to re-edit it to change save path and other tweaks I made, and now it's running fine again.

**Comment by starlilyth** [comment]
I have just pushed another change that will prevent this in the future. Thanks!
