### ISSUE TITLE
Can not switch/modify Pools in Overview

### ISSUE THREAD

**Issue by gnolnos** [starlilyth/Linux-PoolManager#24]
After reinstall the fresh of Bamt 1.4 7xxx and Linux-PoolManager (March 8th update), my rig cannot being access from browser. After, I found out the "poolmanager.conf" file is missing. And found out the "config.pl" will generate it. But I cannot switch or add or modify the pools list from the Overview page. Only in Configuration Editor page I can.

**Comment by starlilyth** [comment]
I have added a starting config back into the initial installer, sorry about that. 

Please be certain your config has the correct API line to allow PoolManager to access to switch or add pools: 
"api-allow" : "W:127.0.0.1",

**Comment by gnolnos** [comment]
I've already have that line on my config file. Any idea?
