### ISSUE TITLE
How can I adjust the scale on my hashrate graph ?

### ISSUE THREAD

**Issue by pmalek** [starlilyth/Linux-PoolManager#26]
I have experience a relatively small scale of my hashrate with comparison to the other indicators (located on the right)

![screenshot from 2014-03-09 03 35 34](https://f.cloud.github.com/assets/739996/2367001/99833a70-a733-11e3-9274-f5e5b7e72e6d.png)

How can I change that ? E.g. in the attached graph change max Hashrate from 7MHash/s to 3MHash/s ?

**Comment by starlilyth** [comment]
It could be done by editing the RRD code in pmgraph.pl, but that sounds like a lot of work. 

It would be easier to adjust the values in pmgraph.colors, which accept transparency values as well as the 6 character color values, so that the display is acceptable.
