### ISSUE TITLE
Can not make changes on config.pl page

### ISSUE THREAD

**Issue by gnolnos** [starlilyth/Linux-PoolManager#28]
When I reinstall Bamt and L-PM (v1.0), the status.pl and config.pl page come up! Bravo! But when I try to save configuration on config.pl page, the page cannot write the config file! When I refresh the page, it's show the default content. I ssh-ed and made changes to "poolmanager.conf" file, refresh the config.pl page on browser, the new content show up. I thought the owner of poolmanager.conf file was wrong, so I "chown" the "poolmanager.conf" to "www-data", try to make changes on config.pl page, everythings was written. => fix that on next release.

**Comment by starlilyth** [comment]
The installer sets www-data as the owner of /opt/ifmi/. 
config.pl creates a brand new poolmanager.conf if one does not exist, like a new install - no poolmanager.conf comes in the zipfile. 
You can test this by renaming your poolmanager.conf and then reloading config.pl. A new conf will be created. 
If this conf does not have the correct permissions, please make sure /opt/ifmi/ is owned by www-data.

**Comment by gnolnos** [comment]
I make a fresh bamt and do wget L-PM on github. It's out of the box new.
So, why the permission is not correct?

On Monday, March 10, 2014, Lily Star notifications@github.com wrote:

> The installer sets www-data as the owner of /opt/ifmi/.
> config.pl creates a brand new poolmanager.conf if one does not exist,
> like a new install - no poolmanager.conf comes in the zipfile.
> You can test this by renaming your poolmanager.conf and then reloading
> config.pl. A new conf will be created.
> If this conf does not have the correct permissions, please make sure
> /opt/ifmi/ is owned by www-data.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/starlilyth/Linux-PoolManager/issues/28#issuecomment-37153858
> .

## 

Trân trọng!

# 

Phan Sơn Long - 096.666.1536
Kênh Truyền hình Quốc phòng Việt Nam
Số 2 Lý Nam Đế, Hàng Mã, Hoàn Kiếm, Hà Nội

**Comment by starlilyth** [comment]
If /opt/ifmi/ is not owned by www-data, then the installer did not set it like it should have. I dont know why, as this works for most people, and your setup should be no different.

**Comment by starlilyth** [comment]
I have written a new installer in Perl, and put an ownwership check in config.pl. 
Please try the latest version and open a new issue if you have problems. 

Thanks!
