### ISSUE TITLE
The miner viewer cannot start/stop the miner

### ISSUE THREAD

**Issue by gnolnos** [starlilyth/Linux-PoolManager#29]
I think that was the permission too. The miner viewer page cannot make the miner being started/stopped or reboot the rig.

**Comment by gnolnos** [comment]
Tried to change ignore BAMT value to yes and no, but no changes!

**Comment by gnolnos** [comment]
Oh, it does stop. But cannot start or reboot the rig.

**Comment by starlilyth** [comment]
It sounds to me as if the permissions were not set correctly by the installer when you installed. Were you root, or did you use sudo?

**Comment by gnolnos** [comment]
Yep, i did everything with root permission. And input root password in
textbox on the page, still nothing.

On Monday, March 10, 2014, Lily Star notifications@github.com wrote:

> It sounds to me as if the permissions were not set correctly by the
> installer when you installed. Were you root, or did you use sudo?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/starlilyth/Linux-PoolManager/issues/29#issuecomment-37153645
> .

## 

Trân trọng!

# 

Phan Sơn Long - 096.666.1536
Kênh Truyền hình Quốc phòng Việt Nam
Số 2 Lý Nam Đế, Hàng Mã, Hoàn Kiếm, Hà Nội

**Comment by starlilyth** [comment]
Tell me how you became root when you installed - what command exactly?

**Comment by gnolnos** [comment]
I ssh-ed into bamt rig by root. Root@myrig

On Monday, March 10, 2014, Lily Star notifications@github.com wrote:

> Tell me how you became root when you installed - what command exactly?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/starlilyth/Linux-PoolManager/issues/29#issuecomment-37154435
> .

## 

Trân trọng!

# 

Phan Sơn Long - 096.666.1536
Kênh Truyền hình Quốc phòng Việt Nam
Số 2 Lý Nam Đế, Hàng Mã, Hoàn Kiếm, Hà Nội

**Comment by starlilyth** [comment]
Perfect, thank you. I appreciate your help, because you are not the only one. Most people can install no problem, but you and one or two others seem to have something different, and I dont know what yet.

**Comment by starlilyth** [comment]
Please try a fresh install with the new installer, and open a new issue if you have trouble. 

Thanks!

**Comment by gnolnos** [comment]
Thank you!

On Wednesday, March 12, 2014, Lily Star notifications@github.com wrote:

> Please try a fresh install with the new installer, and open a new issue if
> you have trouble.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/starlilyth/Linux-PoolManager/issues/29#issuecomment-37385003
> .

## 

Trân trọng!

# 

Phan Sơn Long - 096.666.1536
Kênh Truyền hình Quốc phòng Việt Nam
Số 2 Lý Nam Đế, Hàng Mã, Hoàn Kiếm, Hà Nội

**Comment by monstrfolk** [comment]
same problem. Can stop mining through viewer, but can not start and boot. Using Ubuntu 12.04 x64
I logged into root by sudo -s, then installed.
