### ISSUE TITLE
Double host

### ISSUE THREAD

**Issue by 4D3K** [starlilyth/Linux-PoolManager#3]
I'm using bamt 1.2 with your latest pool manager. At farm view my computers are double showed. In bamt.conf I have defined miner_id like ABMiner001 and in farm view I see one node with exactly the same name "ABMiner001" but below there is the same node with name "abminer001".

**Comment by starlilyth** [comment]
From the FAQs: 
Q: FarmView doesnt work/shows bad or double status in BAMT
A: Make sure mgpumon and broadcast are stopped. Edit bamt.conf, set do_mgpumon to 0 and set do_bcast_status to 0. If you need to use mgpumon, put it on a different port.
