### ISSUE TITLE
Email Alert Notification not working

### ISSUE THREAD

**Issue by jedimstr** [starlilyth/Linux-PoolManager#31]
I saw the new email notification settings in Poolmanager and tried to setup with Gmail first, then with an iCloud account, and neither seems to be working for SMTP. 

No test emails are being sent using the send test button.

**Comment by starlilyth** [comment]
This is the gmail config that is successful for me. 

http://i.imgur.com/cGHQdvA.png

Port 587 also works, and is recommended.

**Comment by jedimstr** [comment]
I got it working with port 587 for TLS thanks!

For some reason the SSL port wasn't working for me.
