### ISSUE TITLE
Local Status View broken on latest commit

### ISSUE THREAD

**Issue by jedimstr** [starlilyth/Linux-PoolManager#32]
After git pulling the latest commit `4fe6ac60430a900236b9f2b7b8b9c63c3b4c72ce` and installing the PM status display of my miner was broken.  It showed that the Miner was Stopped even though CGMiner was running (verified via SSH and from external API access from my mining-dashboard).

The Status works again upon doing a `git reset --hard` back to previous commit `d97c4676072ff2993fe1454f1d0bae5aec38606e` and installing.

API settings in the cgminer.conf were still correct since I was still able to access the running miner from my mining-dashboard on another box.

**Comment by starlilyth** [comment]
I am unable to replicate this, and I am trying to think of an effective troubleshooting test. You might try renaming your poolmanager.conf and letting it recreate. 
You can also try adding verbose: 1 under settings in poolmanager.conf, then watching /var/log/messages with: tail -f /var/log/messages

**Comment by starlilyth** [comment]
There have been several commits since this was opened, and no other reported bugs of this type.

**Comment by jedimstr** [comment]
Still had the issue after another git pull back to HEAD.

Before:
![pm_-_colonialone_-_status](https://cloud.githubusercontent.com/assets/5072618/2558778/9ce88f1c-b75a-11e3-81f9-143fd511a2ed.png)

Git Pull and install:
![sudo_su__su__ssh__ttys003](https://cloud.githubusercontent.com/assets/5072618/2558779/a5a5e974-b75a-11e3-9a55-36f70a026052.png)

After:
![pm_-_colonialone_-_status 2](https://cloud.githubusercontent.com/assets/5072618/2558780/ac8a85f6-b75a-11e3-9167-509c44f7dda8.png)

Was able to fix it though with backing up and removing poolmanager.conf as suggested above.  
To not introduce any potential conflicts, I'm going to have to recreate my previous settings by hand through the interface rather than diff'ing between the two files.  To make it easier for people updating older installs, you may want to recreate the poolmanager.conf as part of your install script and migrating compatible settings over.

**Comment by starlilyth** [comment]
The state of the conf is a little unsettled still so I havent committed to any upgrade script yet, but I have considered what would be the best approach to this. 

Thanks!
