### ISSUE TITLE
Error on upgrading : Can't locate Email/Simple.pm in @INC

### ISSUE THREAD

**Issue by pmalek** [starlilyth/Linux-PoolManager#33]
I have just tried to upgrade by pulling the latest changes from github and running `install-pm.pl` as root but I received the following : 

```
root@rig:/home/USER/programming/Linux-PoolManager# ./install-pm.pl
This will install the IFMI PoolManager for cgminer and clones on Linux.
Are you sure? (y/n) y
It looks like this has been installed before. Do over? (y/n) y
Perl module check
Can't locate Email/Simple.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /us│
r/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at ./install-pm.pl line 45. 
```

**Comment by pmalek** [comment]
After installing 
- libemail-simple-perl
- libemail-sender-perl
- libtry-tiny-perl

it succeeded so I guess those modules are required not only for e-mail notifications but always.

**Comment by starlilyth** [comment]
The installer checks for their presence whether or not you use them, so this is the expected behavior. I will make this a bit clearer int he README. 

Thanks!
