### ISSUE TITLE
Dashboard always shows "Above maximum fan RPM"

### ISSUE THREAD

**Issue by pmalek** [starlilyth/Linux-PoolManager#34]
In `config.pl` there is this variable: 

``` perl
  my $nconf = { 
    monitoring => {
      monitor_temp_hi => '80',
      monitor_temp_lo => '45',
      monitor_load_lo => '0',
      monitor_hash_lo => '200',
      monitor_fan_lo => '1000',
      monitor_fan_hi => '4000',
      monitor_reject_hi => '3',
      do_email => '0',
    },
}
```

but after installing and restarting apache I still get this : 

![screenshot from 2014-03-29 16 56 04](https://cloud.githubusercontent.com/assets/739996/2558786/0969be2c-b75b-11e3-8929-af70b3df794c.png)

**Comment by starlilyth** [comment]
The codeblock you have shown is part of creating a new file if it does not exist. It does not control the running settings. Settings are stored in poolmanager.conf.  

I HIGHLY RECOMMEND you do not edit poolmanager.conf by hand. Please use the settings page to set the values needed.
