### ISSUE TITLE
After last commits cannot reboot (no root password input)

### ISSUE THREAD

**Issue by pmalek** [starlilyth/Linux-PoolManager#38]
After last few commits ( I think 22c788d7e64246a0c872201c40b35a6d4ff90f1a is the one to blame) I do not have root password to enter in reboot menu and cannot get the system to reboot. 

![screenshot from 2014-03-30 21 28 53](https://cloud.githubusercontent.com/assets/739996/2562247/d94485e6-b841-11e3-85b8-adf238725707.png)

**Comment by starlilyth** [comment]
Correct, password boxes are being removed, and I am moving to a slightly different scheme for root required functions. There are some changes to /etc/sudoers, and I have tried to make the installer account for it, but it may not have done the right thing. 
Currently your /etc/sudoers should look like this: 
www-data ALL=(root)NOPASSWD: /opt/ifmi/mcontrol
Defaults:www-data rootpw
www-data ALL=(root)/bin/cp

The mcontrol file is only used for start and boot.

**Comment by pmalek** [comment]
My sudoers file 

```
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL:ALL) ALL
USER  ALL=(ALL:ALL) NOPASSWD:ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL

#includedir /etc/sudoers.d
www-data ALL=(ALL:ALL) /opt/ifmi/mcontrol,/bin/cp,/sbin/reboot
```

**Comment by starlilyth** [comment]
Remove the last line: 
    www-data ALL=(ALL:ALL) /opt/ifmi/mcontrol,/bin/cp,/sbin/reboot

Replace with these lines: 
    www-data ALL=(root)NOPASSWD: /opt/ifmi/mcontrol 
    Defaults:www-data rootpw
    www-data ALL=(root)/bin/cp

**Comment by starlilyth** [comment]
Please let me know if this corrected your issue.

**Comment by pmalek** [comment]
This somehow helps as I can see the broadcast that the system is going for reboot but it won't reboot (or maybe it will take quite long) but maybe that's a Ubuntu issue.

**Comment by starlilyth** [comment]
If you have gotten the broadcast shutdown message, PM has done what it is supposed to do!
