### ISSUE TITLE
Graphs are not updated after last commits

### ISSUE THREAD

**Issue by pmalek** [starlilyth/Linux-PoolManager#39]
I have noticed that graphs are not updates after pulling the last changes. I think this may be an issue with permissions.

My `/opt/ifmi` directory has the following files with following permissions:

```
-rwxr-xr-x 1 root     root  19K mar 30 21:18 farmview
-rwxr-xr-x 1 root     root  19K mar  7 19:17 farmview.back
-rwxr-xr-x 1 root     root 1,2K mar 30 21:18 mcontrol
-rwxr-xr-x 1 root     root 1,3K mar  7 19:17 mcontrol.back
-rwxr-xr-x 1 root     root  13K mar 30 21:18 pm-common.pl
-rw-r--r-- 1 root     root  22K mar  7 19:17 pm-common.pl.back
-rwxr-xr-x 1 root     root 8,8K mar 30 21:18 pmgraph.pl
-rwxr-xr-x 1 root     root  11K mar 30 21:18 pmnotify.pl
-rw-r--r-- 1 www-data root  849 mar 29 20:16 poolmanager.conf
-rw-r--r-- 1 root     root 3,1K mar  7 19:17 poolmanager.conf.back
drwxr-xr-x 2 root     root 4,0K mar 22 21:06 rrdtool
-rwxr-xr-x 1 root     root 2,5K mar 30 21:18 run-poolmanager.pl
-rwxr-xr-x 1 root     root 1,5K mar  7 19:17 run-poolmanager.pl.back
-rwxr-xr-x 1 root     root 2,8K mar 30 21:18 sendstatus.pl
-rwxr-xr-x 1 root     root 2,4K mar  7 19:17 sendstatus.pl.back
```

changing them all to `www-data:www-data` didn't help

**Comment by starlilyth** [comment]
Please try to execute /opt/ifmi/pmgraph.pl as root. It may correct the issue even if there are no errors.

**Comment by pmalek** [comment]
It did clear the graphs but didn't restarting their drawing. I have even tried reinstalling (with remove-pm.sh) but that didn't help either.

**Comment by starlilyth** [comment]
If you are able to execute pmgraph.pl without errors but your graphs are not drawing, it is a cron problem. Please make sure your /etc/crontab has the following line: 
    \* \* \* \* \* root /opt/ifmi/run-poolmanager.pl

If you are still not drawing, please check that your cron daemon is working normally.

**Comment by pmalek** [comment]
Somehow they are still not drawn.

**Comment by poxus** [comment]
cron daemon is wrking almost normally, just install:
libproc-pid-file-perl and libemail-sender-transport-smtp-tls-perl

But i still have "atitweak" error:
./run-poolmanager.pl
sh 1 /usr/local/bin/atitweak: not found

apache2/error.log:
[error] sh: 1: /usr/local/bin/atitweak: not found, referer: https://192.168.0.1/cgi-bin/status.pl
[error] Use of uninitialized value $poolnum in hash element at /usr/lib/cgi-bin/status.pl line 743., referer: https://192.168.0.1/cgi-bin/status.pl
[error] Use of uninitialized value $poola in concatenation (.) or string at /usr/lib/cgi-bin/status.pl line 815., referer: https://192.168.0.1//cgi-bin/status.pl

/opt/ifmi/pm-common.pl
sub getFreshGPUData {
  ...
    my $res = `DISPLAY=:0.0 /usr/local/bin/atitweak -s`;
 ...

**Comment by pmalek** [comment]
I also keep getting those errors with `atitweak` and `Use of uninitialized value $poolnum in hash element`

**Comment by starlilyth** [comment]
The original BAMT used atitweak almost exclusively to get gpu data. I get all the data direct from cgminer, with the exception of the reported card name. 

I am confused about how this JUST NOW a problem. I will fix up the error reporting for when atitweak is missing, but I am not sure what kind of miner setup you have that doesnt have atitweak.

**Comment by poxus** [comment]
I use original debian and original cgminer 3.7.2 with original AMD-APP 'n AMD-ADL SDK. Is not that enough? And i have never seen something called "atitweak" + you didnt write this in system requirements.
it is not a problem (may be), but i dont like errors in log files =)

**Comment by starlilyth** [comment]
Fixed in latest commit.
