### ISSUE TITLE
/usr/local/bin/atitweak in apache's error.log

### ISSUE THREAD

**Issue by poxus** [starlilyth/Linux-PoolManager#40]
i see a lot of error messages in error.log (/var/log/apache2/error.log) such as:
"sh: 1: /usr/local/bin/atitweak: not found, referer: https://192.168.0.1/cgi-bin/status.pl?tok=1"

p.s. i use first official release (because of not drawing graphs in later releases, still cant configure). 
there are theese errors in later releases too

p.p.s
also there are some errors:
Argument "\x{31}\x{2e}..." isn't numeric in numeric ne (!=) at /usr/lib/cgi-bin/config.pl line 87., r
eferer: https://192.168.0.1/cgi-bin/status.pl?miner=
Argument "1.2.0+" isn't numeric in numeric ne (!=) at /usr/lib/cgi-bin/config.pl line 87., referer: https://192.168.0.1/cgi-bin/status.pl?miner=
Argument "\x{31}\x{2e}..." isn't numeric in numeric ne (!=) at /usr/lib/cgi-bin/config.pl line 87., r
eferer: https://192.168.0.1/cgi-bin/config.pl
Argument "1.2.0+" isn't numeric in numeric ne (!=) at /usr/lib/cgi-bin/config.pl line 87., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nht in string ne at /usr/lib/cgi-bin/config.pl line 91., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nlt in string ne at /usr/lib/cgi-bin/config.pl line 96., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nll in string ne at /usr/lib/cgi-bin/config.pl line 101., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nhl in string ne at /usr/lib/cgi-bin/config.pl line 106., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nfl in string ne at /usr/lib/cgi-bin/config.pl line 111., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nfh in string ne at /usr/lib/cgi-bin/config.pl line 116., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nrh in string ne at /usr/lib/cgi-bin/config.pl line 121., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $doe in string ne at /usr/lib/cgi-bin/config.pl line 126., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $ncmc in string ne at /usr/lib/cgi-bin/config.pl line 129., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nmconfig in string ne at /usr/lib/cgi-bin/config.pl line 132., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $mdel in string ne at /usr/lib/cgi-bin/config.pl line 180., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nap in string ne at /usr/lib/cgi-bin/config.pl line 187., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $ibamt in string ne at /usr/lib/cgi-bin/config.pl line 192., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nml in string ne at /usr/lib/cgi-bin/config.pl line 195., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nscss in string ne at /usr/lib/cgi-bin/config.pl line 197., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nfcss in string ne at /usr/lib/cgi-bin/config.pl line 199., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $ngcf in string ne at /usr/lib/cgi-bin/config.pl line 204., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nha in string ne at /usr/lib/cgi-bin/config.pl line 206., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nbcast in string ne at /usr/lib/cgi-bin/config.pl line 210., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nbp in string ne at /usr/lib/cgi-bin/config.pl line 212., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nfarmview in string ne at /usr/lib/cgi-bin/config.pl line 217., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nlp in string ne at /usr/lib/cgi-bin/config.pl line 219., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $dds in string ne at /usr/lib/cgi-bin/config.pl line 225., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nst in string ne at /usr/lib/cgi-bin/config.pl line 228., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nsf in string ne at /usr/lib/cgi-bin/config.pl line 230., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nsh in string ne at /usr/lib/cgi-bin/config.pl line 232., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nsmp in string ne at /usr/lib/cgi-bin/config.pl line 234., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nssl in string ne at /usr/lib/cgi-bin/config.pl line 239., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $ntls in string ne at /usr/lib/cgi-bin/config.pl line 241., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nsau in string ne at /usr/lib/cgi-bin/config.pl line 243., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nsap in string ne at /usr/lib/cgi-bin/config.pl line 245., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $nmw in string ne at /usr/lib/cgi-bin/config.pl line 247., referer: https://192.168.0.1/cgi-bin/config.pl
Use of uninitialized value $se in string ne at /usr/lib/cgi-bin/config.pl line 253., referer: https://192.168.0.1/cgi-bin/config.pl

**Comment by starlilyth** [comment]
Please use the newest release which has corrected these issues.
