### ISSUE TITLE
A big great error

### ISSUE THREAD

**Issue by ysilvela** [starlilyth/Linux-PoolManager#42]
I found a great important error. I don't the reason but a few days ago I install Linux-Poolmanager and i set three pools (one main an two in backup) and yesterday at 1.30 AM my rig was down suddently. Logicaly I not know the problem for hours at least 9.00 AM.

I'm lose a lot of LTC, but the main issue is ¿If I not detect the  downtime of rig? ¿When i restart and unistall this malware software?

**Comment by starlilyth** [comment]
PoolManager is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

If you are unhappy with PoolManager you may run remove-pm.sh in the same directory you installed from. 

Please do not make accusations about 'malware' when you can view every line of code for yourself and see that it is not true.

**Comment by ysilvela** [comment]
It's true. This software isnt a malware. I'm not explain correctly.

But the true is that it have a great issue because allow not detect the miner shutdown. Its dangerous.

I comment it to aid solve it

**Comment by starlilyth** [comment]
Thank you for your report. It is difficult to understand the problem you are having without more information.
