### ISSUE TITLE
Gridseed and Pi support

### ISSUE THREAD

**Issue by starlilyth** [starlilyth/Linux-PoolManager#45]
Hi Star- So I am a bit new to GIT - hopefully I didn't screw anything up on the site there! 

First, thank you for your work- it's being used in several places now- PIMP is the big one that comes to mind. Nice job. Anyway, as far as the gridseed ASIC PI miners go, i found out there are several issues so it's most likely not worth your time but here are a few issues I noticed if your curious: 

The api call for cgminer (or sgminer) has a different ID for checking cpucount or gpucount, for ASICS its asccount. So along with that, calls to specific devices are asc1 versus gpu1. Obviously ASIC devices won't have temps or fans speeds and it's complicated by sgminer uses xintensity along with regular intensity that messes up standard GPU calls. Also the Pi's are very small foot print, tiny CPU's. I tried tossing it on a few but when the status.pl runs it spikes the PI CPU up to 100%. Typically PI will use lighttpd instead of apache2 as it was designed for fast, low overhead integrated devices. Of course lighttpd configs are not equal to apache2 so thats even more of a bummer. 

As crypto moves forward, scrypt-j and scrypt asics are becoming more popular. If this is something your thinking about working on, please let me know. I can supply some API ASIC dumps, or even open a live one up to an internet address for you to play with. Seems like a lot of work though, just thought I'd offer the help .. Cheers
https://github.com/Vap0rz

**Comment by starlilyth** [comment]
I have been investigating support for ASIC devices, Gridseeds in particular, but the biggest roadblock to my development is access to the hardware used. I think it would not be difficult to port however, and create "SeedManager". 

PoolManager was designed with no resource constraints, as typical PC based miners have more than enough resources to spare for driving it. The requirements for PoolManager are not Apache specific - Apache is required by the installer to set up https redirection automatically, and to provide htacces security. Any web server capable of serving CGI can be used, so lighthttpd should work fine provided it has the correct CGI bits. 

Lily

**Comment by Vap0rz** [comment]
Hi Lily,
Please delete if this doesn't belong here, or let me know if there is a better way to communicate this...
ASIC Greedsid API responses from CGMINER 3.7.2 modified (standard for gridseed) :
[asccount]
STATUS=S,When=1397079251,Code=104,Msg=ASC count,Description=cgminer 3.7.2|ASCS,Count=16|
[ascidentify|N]
STATUS=W,When=1397079319,Code=114,Msg=ASC0 does not support identify,Description=cgminer 3.7.2|
[asc|N]
STATUS=S,When=1397079504,Code=106,Msg=ASC0,Description=cgminer 3.7.2|ASC=0,Name=GSD,ID=0,Enabled=Y,Status=Alive,Temperature=0.00,MHS av=0.36,MHS 5s=0.36,Accepted=1367,Rejected=6,Hardware Errors=1,Utility=0.26,Last Share Pool=7,Last Share Time=1397079412,Total MH=112678.5718,Diff1 Work=1397,Difficulty Accepted=1638496.00000000,Difficulty Rejected=7040.00000000,Last Share Difficulty=256.00000000,No Device=false,Last Valid Work=1397079412,Device Hardware%=0.0715,Device Rejected%=503.9370,Device Elapsed=311521|
[devs]
STATUS=S,When=1397079688,Code=9,Msg=16 ASC(s) - ,Description=cgminer 3.7.2|ASC=0,Name=GSD,ID=0,Enabled=Y,Status=Alive,Temperature=0.00,MHS av=0.36,MHS 5s=0.36,Accepted=1369,Rejected=6,Hardware Errors=1,Utility=0.26,Last Share Pool=7,Last Share Time=1397079571,Total MH=112745.2602,Diff1 Work=1400,Difficulty Accepted=1639008.00000000,Difficulty Rejected=7040.00000000,Last Share Difficulty=256.00000000,No Device=false,Last Valid Work=1397079601,Device Hardware%=0.0714,Device Rejected%=502.8571,Device Elapsed=311702|ASC=1,Name=GSD,ID=1,Enabled=Y,Status=Alive,Temperature=0.00,MHS av=0.36,MHS 5s=0.36,Accepted=1100,Rejected=5,Hardware Errors=1,Utility=0.21,Last Share Pool=7,Last Share Time=1397079670,Total MH=112743.7516,Diff1 Work=1121,Difficulty Accepted=1326464.00000000,Difficulty Rejected=6080.00000000,Last Share Difficulty=256.00000000,No Device=false,Last Valid Work=1397079670,Device Hardware%=0.0891,Device Rejected%=542.3729,Device Elapsed=311702|ASC=2,Name=GSD,ID=2,Enabled=Y,Status=Alive,Temperature=0.00,MHS av=0.36,MHS 5s=0.36,Accepted=1378,Rejected=6,Hardware Errors=0,Utility=0.27,Last Share Pool=7,Last Share Time=1397079575,Total MH=112744.9059,Diff1 Work=1406,Difficulty Accepted=1603776.00000000,Difficulty Rejected=7616.00000000,Last Share -truncated the rest|
[devdetails]
STATUS=S,When=1397079863,Code=69,Msg=Device Details,Description=cgminer 3.7.2|DEVDETAILS=0,Name=GSD,ID=0,Driver=gridseed,Kernel=,Model=,Device Path=1:23|DEVDETAILS=1,Name=GSD,ID=1,Driver=gridseed,Kernel=,Model=,Device Path=1:22|DEVDETAILS=2,Name=GSD,ID=2,Driver=gridseed,Kernel=,Model=,Device Path=1:21|  --truncated

Also available [ascenable|N], [ascdisable|N] and [ascset](not much to set though)
Thanks again!

**Comment by starlilyth** [comment]
This is great! Ill see what I can do. Thanks :)

**Comment by starlilyth** [comment]
I have made a first pass at trying to port this over. It still uses Apache, but if I can get it working correctly it will be easy enough to change the installer for lighthttp. If you have some gridseeds on a PC please give it a try: https://github.com/starlilyth/Linux-SeedManager
