### ISSUE TITLE
cannot write to its config!

### ISSUE THREAD

**Issue by evaliuta** [starlilyth/Linux-PoolManager#59]
Hello,
i have tried chmod
mv
set privilegies
nothing helped
please help whit this

i have instaled pool manager on ubuntu 13.10 server 64 bit and runing vertminer

Many thanx

**Comment by LinuxETC** [comment]
Do an `ls -lh` on your configuration file(s) and post the results please.

**Comment by evaliuta** [comment]
http://prntscr.com/3ump6m

im changed user and group to user user, but the same

**Comment by starlilyth** [comment]
This file needs to be owned by the web server user, not root.

**Comment by evaliuta** [comment]
i have made owner and group user user, but writes the same

**Comment by starlilyth** [comment]
That is incorrect. The web server user on ubuntu is "www-data". Please make the file owned by this user. The /opt/ifmi directory also needs to be owned by this user. 
Alternately, you can delete the file, and it will be recreated when you visit the settings page. 

If you installed using the installer, how did your conf file come to have the wrong permissions?

**Comment by evaliuta** [comment]
i have configured this file in root terminal

done  its working :) 

thanks

**Comment by starlilyth** [comment]
There is in fact a giant note at the top of the file saying not to do that. Please do not open issues on problems you have created for yourself.

**Comment by evaliuta** [comment]
sorry :)
